#!/bin/bash


pydir="$(dirname "$(readlink -f "$0")")"
python ${pydir}/plot-distribution.py position -o position -v --np
python ${pydir}/plot-planes.py fluid density -o density -v --min-max
python ${pydir}/plot-planes.py fluid potential -o potential -v --min-max --colormap seismic

